language: scala
scala:
  - 2.11.8
  - 2.12.1
  - 2.13.2
jdk:
  - oraclejdk8
script: sbt clean test
cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache
notifications:
  slack: thenewmotion:AXSluctig1mmZbeKRDeeY41s
